#include "export.h"
#include "db.h"
#include "qso.h"

/*
 * Export the current logbook to CSV, using the database layer when available.
 *
 * @param filename Output file path.
 * @return 0 on success, or -1 on failure.
 */
int export_csv(const char *filename) {
  if (db_export_csv(filename) == 0)
    return 0;

  FILE *f = fopen(filename, "w");
  if (!f)
    return -1;

  fprintf(f, "DATE,UTC,CALL,FREQ,BAND,MODE,RST,COMMENTS,COUNTRY\n");

  for (int i = 0; i < qso_count; i++) {
    QSO *q = &logbook[i];

    if (q->invalid)
      continue;

        fprintf(f, "%s,%s,%s,%d,%s,%s,%s,%s,%s\n", q->date, q->utc, q->call,
          q->freq, q->band, q->mode, q->rst, q->comments, q->country);
  }

  fclose(f);
  return 0;
}

/*
 * Export the current logbook to ADIF, using the database layer when available.
 *
 * @param filename Output file path.
 * @return 0 on success, or -1 on failure.
 */
int export_adif(const char *filename) {
  if (db_export_adif(filename) == 0)
    return 0;

  FILE *f = fopen(filename, "w");
  if (!f)
    return -1;

  fprintf(f, "Generated by Logger\n");
  fprintf(f, "<EOH>\n");

  for (int i = 0; i < qso_count; i++) {
    QSO *q = &logbook[i];

    if (q->invalid)
      continue;

    fprintf(f, "<CALL:%zu>%s", strlen(q->call), q->call);
    fprintf(f, "<QSO_DATE:8>%s", q->date);
    fprintf(f, "<TIME_ON:4>%s", q->utc);
    fprintf(f, "<FREQ:9>%.6f", q->freq / 1000.0);
    fprintf(f, "<BAND:%zu>%s", strlen(q->band), q->band);
    fprintf(f, "<MODE:%zu>%s", strlen(q->mode), q->mode);
    fprintf(f, "<RST_SENT:%zu>%s", strlen(q->rst), q->rst);
    fprintf(f, "<RST_RCVD:%zu>%s", strlen(q->rst), q->rst);
    if (strlen(q->comments)) {
      fprintf(f, "<COMMENT:%zu>%s", strlen(q->comments), q->comments);
    }

    if (strlen(q->country)) {
      fprintf(f, "<COUNTRY:%zu>%s", strlen(q->country), q->country);
    }

    fprintf(f, "<EOR>\n");
  }

  fclose(f);
  return 0;
}
