LAT=52.2297
LON=21.0122
LOCATOR=JO92DF

DXC_HOST=telnet.reversebeacon.net
DXC_PORT=7000
DXC_CALL=SP6AA

CAT_MODEL=2
CAT_DEVICE=/dev/ttyUSB0
CAT_BAUD=9600
CAT_DATA_BITS=8
CAT_STOP_BITS=1
CAT_PARITY=None
CAT_HANDSHAKE=None
CAT_MODE_FROM_RIG=0

